// This file is auto-generated by @hey-api/openapi-ts

export const $Message = {
    type: 'object',
    required: ['ok', 'message'],
    properties: {
        ok: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const $TokenRequest = {
    type: 'object',
    required: ['password'],
    properties: {
        password: {
            type: 'string'
        }
    }
} as const;

export const $TokenResponse = {
    type: 'object',
    required: ['token'],
    properties: {
        token: {
            type: 'string'
        }
    }
} as const;

export const $Notes = {
    type: 'object',
    required: ['notes'],
    properties: {
        notes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        nextPage: {
            type: 'string'
        }
    }
} as const;

export const $Note = {
    type: 'object',
    required: ['key', 'body'],
    properties: {
        key: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        modified: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;