// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetHealthResponse, PostTokenData, PostTokenResponse, GetNoteData, GetNoteResponse, PostNoteData, PostNoteResponse, GetNoteByKeyData, GetNoteByKeyResponse, PutNoteByKeyData, PutNoteByKeyResponse } from './types.gen';

/**
 * @returns Message
 * @throws ApiError
 */
export const getHealth = (): CancelablePromise<GetHealthResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/health'
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns TokenResponse
 * @returns Message
 * @throws ApiError
 */
export const postToken = (data: PostTokenData = {}): CancelablePromise<PostTokenResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/token',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.authorization
 * @param data.q
 * @param data.dir
 * @param data.page
 * @returns Notes
 * @returns Message
 * @throws ApiError
 */
export const getNote = (data: GetNoteData): CancelablePromise<GetNoteResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/note',
    headers: {
        Authorization: data.authorization
    },
    query: {
        q: data.q,
        dir: data.dir,
        page: data.page
    }
}); };

/**
 * @param data The data for the request.
 * @param data.authorization
 * @param data.requestBody
 * @returns Note
 * @returns Message
 * @throws ApiError
 */
export const postNote = (data: PostNoteData): CancelablePromise<PostNoteResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/note',
    headers: {
        Authorization: data.authorization
    },
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.authorization
 * @param data.key
 * @returns Note
 * @returns Message
 * @throws ApiError
 */
export const getNoteByKey = (data: GetNoteByKeyData): CancelablePromise<GetNoteByKeyResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/note/{key}',
    path: {
        key: data.key
    },
    headers: {
        Authorization: data.authorization
    }
}); };

/**
 * @param data The data for the request.
 * @param data.authorization
 * @param data.key
 * @param data.requestBody
 * @returns Note
 * @returns Message
 * @throws ApiError
 */
export const putNoteByKey = (data: PutNoteByKeyData): CancelablePromise<PutNoteByKeyResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/note/{key}',
    path: {
        key: data.key
    },
    headers: {
        Authorization: data.authorization
    },
    body: data.requestBody,
    mediaType: 'application/json'
}); };